"""simplify auth schema

Revision ID: 001_simplify_auth
Revises: 
Create Date: 2025-01-02 00:53:05.386

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001_simplify_auth'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'last_password_change')
    op.drop_column('student', 'session_token')
    op.drop_column('student', 'password_reset_token')
    op.drop_column('student', 'password_reset_expiry')
    op.drop_column('student', 'mfa_secret')
    op.drop_column('student', 'mfa_enabled')
    op.drop_column('student', 'last_activity')
    op.drop_column('student', 'password_history')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password_history', sa.JSON(), nullable=True))
    op.add_column('student', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('student', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('mfa_secret', sa.String(length=32), nullable=True))
    op.add_column('student', sa.Column('password_reset_expiry', sa.DateTime(), nullable=True))
    op.add_column('student', sa.Column('password_reset_token', sa.String(length=100), nullable=True))
    op.add_column('student', sa.Column('session_token', sa.String(length=64), nullable=True))
    op.add_column('student', sa.Column('last_password_change', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
